name: Bump

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  bump-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Read released version
        id: get_ver
        run: |
          VER=$(grep -oP '(?<=__version__\s*=\s*\")[^\"]+' lib_version/version.py)
          echo "version=$VER" >> "$GITHUB_OUTPUT"

      - name: Bump to pre-release version
        run: |
          git fetch origin main
          git checkout -B version-bump origin/main
          IFS='.' read -r MAJOR MINOR PATCH <<<"${{ steps.get_ver.outputs.version%%-* }}"
          NEXT="$MAJOR.$MINOR.$((PATCH+1))-pre"
          sed -E "s/__version__ = \".*\"/__version__ = \"$NEXT\"/" lib_version/version.py > version.tmp.py
          mv version.tmp.py lib_version/version.py
          git add lib_version/version.py
          git commit -m "chore: bump to $NEXT [skip ci]"
          git push origin version-bump:main

      - name: Cleanup
        if: always()
        run: git branch -D version-bump || true
