name: Delivery

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-tag pre-releases
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          default_bump: patch
          release_branches: ""
          pre_release_branches: main
          default_prerelease_bump: prerelease
          append_to_pre_release_tag: pre

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/*
