name: Delivery

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: git fetch --tags

      - id: compute
        run: |
          LATEST=$(git tag --list 'v*-pre*' --sort=-v:refname | head -n1)
          if [ -z "$LATEST" ]; then
            BASE=$(git tag --list 'v*.*.*' --sort=-v:refname | head -n1 | sed 's/^v//')
            NUM=1
          else
            BASE=${LATEST#v}
            BASE=${BASE%-pre*}
            NUM=${LATEST##*-pre}
            NUM=$((NUM+1))
          fi
          NEXT="$BASE-pre$NUM"
          echo "next=$NEXT" >> $GITHUB_OUTPUT

      - run: |
          sed -E 's/^__version__ = ".*"/__version__ = "'"${{ steps.compute.outputs.next }}"'"/' \
            lib_version/version.py > tmp && mv tmp lib_version/version.py

      - run: |
          git add lib_version/version.py
          git commit -m "Version bumped to ${{ steps.compute.outputs.next }}"

      - run: |
          git tag "v${{ steps.compute.outputs.next }}"
          git push origin main --tags