name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - id: extract
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - run: |
          git fetch origin main:main
          git checkout main

      - run: |
          sed -E 's/^__version__ = ".*"/__version__ = "'"${{ steps.extract.outputs.version }}"'"/' \
            lib_version/version.py > tmp && mv tmp lib_version/version.py

      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add lib_version/version.py
          git commit -m "chore: release ${{ steps.extract.outputs.version }}"
          git push origin main --tags

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: compute
        run: |
          IFS='.' read MAJOR MINOR PATCH <<<"${{ steps.extract.outputs.version }}"
          NEXT="$MAJOR.$MINOR.$((PATCH+1))-pre1"
          echo "next=$NEXT" >> $GITHUB_OUTPUT

      - run: |
          sed -E 's/^__version__ = ".*"/__version__ = "'"${{ steps.compute.outputs.next }}"'"/' \
            lib_version/version.py > tmp && mv tmp lib_version/version.py

      - run: |
          git add lib_version/version.py
          git commit -m "Version bumped to ${{ steps.compute.outputs.next }}"
          git tag "v${{ steps.compute.outputs.next }}"
          git push origin main --tags