name: Release

on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Release level (patch, minor, major)'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bump stable version & create tag
        id: stable
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.bump_level || 'patch' }}
          tag_prefix: v
          release_branches: main

      - name: Write stable version to file
        run: |
          python scripts/write_version.py
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add lib_version/version.py
          git commit -m "chore: release ${{ steps.stable.outputs.new_tag }}"
          git push origin main

      - uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.stable.outputs.new_tag }}
          release_name: ${{ steps.stable.outputs.new_tag }}

      - name: Bump prerelease version & create tag
        id: pre
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_prerelease_bump: prerelease
          append_to_pre_release_tag: pre
          tag_prefix: v
          release_branches: '_NONE_'
          pre_release_branches: main

      - name: Write prerelease version to file
        run: |
          python scripts/write_version.py
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add lib_version/version.py
          git commit -m "chore: bump to ${{ steps.pre.outputs.new_tag }}"
          git push origin main --tags
