name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Extract version from tag
        id: extract
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Write stable version
        run: |
          sed -E 's/^__version__ = ".*"/__version__ = "'"${{ steps.extract.outputs.version }}"'"/' \
            lib_version/__version__.py > tmp && mv tmp lib_version/__version__.py

      - name: Commit stable version
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add lib_version/__version__.py
          git commit -m "chore: release ${{ steps.extract.outputs.version }}"
          git push origin HEAD

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}

      - name: Compute next pre-release
        id: next
        run: |
          IFS='.' read MAJOR MINOR PATCH <<<"${{ steps.extract.outputs.version }}"
          NEXT="$MAJOR.$MINOR.$((PATCH+1))-pre1"
          echo "next=$NEXT" >> $GITHUB_OUTPUT

      - name: Write pre-release version
        run: |
          sed -E 's/^__version__ = ".*"/__version__ = "'"${{ steps.next.outputs.next }}"'"/' \
            lib_version/__version__.py > tmp && mv tmp lib_version/__version__.py

      - name: Commit & tag pre-release
        run: |
          git add lib_version/__version__.py
          git commit -m "chore: bump to ${{ steps.next.outputs.next }}"
          git tag "v${{ steps.next.outputs.next }}"
          git push origin HEAD --tags
